###
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Jerry Smith9",
  "username": "jerrysmith5",
  "email": "jerry.smith5@email.com",
  "password": "123456"
}

###
GET http://localhost:3000/user
Content-Type: application/json
